################################################################################
# Makefile for Correlation
################################################################################

KERNEL:=testfloat2
all: $(KERNEL).elf

RELATIVE:=../..
-include $(RELATIVE)/util/makefile.master

