package pt.up.fe.specs.binarytranslation.graphs;

import java.util.ArrayList;
import java.util.List;

import pt.up.fe.specs.binarytranslation.instruction.Instruction;
import pt.up.fe.specs.binarytranslation.instruction.Operand;

public class GraphNode {

    private int nodenr;
    private int level;
    // private int numchildren;
    // private int numparents;
    private final Instruction inst;

    // These two lists are generated by converting the
    // Operand list in the "inst" reference into graphinputs/outputs.
    // The inst variable retains the original information for whatever lookup is required
    private List<GraphInput> inputs;
    private List<GraphOutput> outputs;

    // assigns IDs to nodes as they are instantiated?
    // private static int nodecounter = 0;
    // TODO: this doesnt work properly currently (since counting carries over multiple graphs), but will do if some of
    // this code is moved to a BinarySegmentGraph generator

    public GraphNode(Instruction i) {

        // this.op = new GraphOperation(GraphNodeCatalogue.convertInstruction(i));
        this.inst = i;
        this.nodenr = -1;

        // set first level as 0
        this.level = 0;

        // convert operations in instruction to node inputs/outputs
        this.inputs = new ArrayList<GraphInput>();
        this.outputs = new ArrayList<GraphOutput>();

        for (Operand op : i.getData().getOperands()) {
            if (op.isRead())
                this.inputs.add(new GraphInput(op));

            else if (op.isWrite())
                this.outputs.add(new GraphOutput(op));
        }
    }

    // should only need to call this once
    public void setNodenr(int nodenr) {
        this.nodenr = nodenr;
    }

    public Instruction getInst() {
        return inst;
    }

    public List<GraphInput> getInputs() {
        return inputs;
    }

    public List<GraphOutput> getOutputs() {
        return outputs;
    }

    public int getLevel() {
        return level;
    }

    public void setLevel(int level) {
        this.level = level;
    }

    /*
    public int getNumchildren() {
        return numchildren;
    }
    
    public int getNumparents() {
        return numparents;
    }
    */
    public int getNodeNr() {
        return nodenr;
    }

    public String getRepresentation() {
        return Integer.toString(this.nodenr) + ":" + this.inst.getName();
    }
}
